def substring_hash(s, power, modulo, k, hashValue):
    s_len = len(s)
    hash_result = 0
    result_idx = None
    for idx in range(s_len - 1, -1, -1):
        hash_result = (hash_result + val(s[idx])) % modulo
        if idx <= s_len - k:
            if hash_result == hashValue:
                result_idx = idx
            hash_result = (hash_result - (val(s[idx + k - 1]) * (power ** (k - 1))) % modulo + modulo) % modulo
            hash_result = (hash_result * power) % modulo
        else:
            hash_result = (hash_result * power) % modulo
    return s[result_idx: result_idx + k]


def val(let):
    return ord(let) - ord('a') + 1

s = "qewhvotxijxctihmemjtbxhitjrldvvqovzsrokchwounwacwsnxbkrlkefudxozdduwchfeugcjrlvhctudwdmnbokyfyficbgobrsitapxgizzcqgpyhlytptzfhokmhopbmpqdgwrwunwddssxcbazweyrebkglejntgnpeyfwibtdzsdhhwhperjaouqnfxvjufchbogtreiyyamocytgiszaunnjgoikxjxkwkwzhupqfktskkzvmmswipcsxpiuyhtodrpljbkwwvbehkdrvqurzsnlxfzclmwmpabkhlnwomoigplbiwzqpxeugbclwonxkhvlgtgpuuthkkpkbabmuttmudlypxcvgudcuunaqsgunilwrczpeatvdyxmlphzjltnxyfccjxmblvciytomslsrpidpygwbguxzzulqyhwuojeayaonqhaqjnbecpipzyobhevpuzadjzxfspqeuhfqzkqikbamkajzwwplopqfkrhilhvjffxowbfgtccpvuyrtbarehrwuvzoyxcuzpzhramjsedksnolzomnibrayztwmmoyvouavuqezzerxxswnhhrveughavtjevhgvvwtucubqlbdsnhemwpebroxidpgkbnxkewiovoqwicpgnaqdapbeguzgrolndykcoacbyrnyqgmzobnkllslzefwfhqqcfkfkoiftcfgumsvoavjbcglgeriwechchmoezsayqymazteqpwxikjszfwplnihvuvyyvjcahvpylfuiffutplkvwkyrgzraegboubdqtrtjijisgjhaqkgbbmvzzlkdruxogczwagmxftsesqtwxxplnaiowmpzxukkkgpvgejimfffhzulozmyukbcxklluvfgnhrbvuldiwavzqjgfhtfweyogsznrocusnuuttypwkuefjahearxgymkaeiljvnmxdrypckrzyavqxinwqcghrpixbzpmalihhcliqabjqwfwcgmewrhtafkqvvuwwvfuccyswclhxfbzgdtvnphwqnewehtuqsbaanzmjewyzwecjxnamadqsstqjjedzqiobhzjngszprkzrjyxqnwrgxroktpvumjuootvllnelbpacqjzqetehqtvvawaqslxwkbkigdlbvvqefnzsszdtdkdtgcuebyanikjlultyofyahhtcmvrdyvlevlkooefrgrgaehwnqnlyqpvovkmfkglefrmqeovqcphgzzdaflkoeecoiossmmcnltdlytqvbuurgtjolmwllvraztzgqjaqocudykyvzoyqqalccguysiuzggotypxajxcwwqekvudlasbwppzitnhuigebrpawyziieepsrclxuhzacsliwmijdzpdpmkfpvybeqkcquixtwcqiuspehcdoyuhfwcmcctdpebgibenfenxlwejxuoabypwwnvjpurzsgmloregohjmxlobbqkxntwidoeabvkjjotbjxixosmcdpcrnltvzuhnxnrzhxxzpzbtqdulqrhqfjlkwgtyzqonwxveehwrxbrjfijszzvxwxooetexntoprvhfkifoqkqilgkcbbuhirjmqkgkqhbqysouadvuodczczgfbkgpkpwixnxseeefnskbpcbmwkszlnvmwgemgyycthztibjrvgtarumxplvcwilbijxssybggrbigwpuvjiiadprsvsisdlwdtlxoyofnszyohilngtxogwiisewytobrotskefuykmlgpyyhjpkhigsewfuoptcnscblbldixxaoexlqgplrvqruyqfgcnqwzjxgrzfuxpmiejertazgxzcrejtirdtsonaqmtgeyindijhbkujsdlcikvvitwhqsrhfdwqrmkgpaybsgvoqsnssznhmqxpdcwzyrqjvklotwfoqqotxoefzdntzvdcjxcbrzxtkkaqehfodvandtdipjlnrbmxwyprhgmxuucftovdvwkihvswutawuvucepnvgxayswzqtykrdszpivmlxmylmjedrxzyubtuinvaltzfbcwjfiztbikefwbhajaatygotbbvtvvdbjbkritjbrnillvpgjxjlapkwwgieodalhtfftiqziaqamvpbymgyrknpeqoyzsvpiparhvmglejtkijgczysejnoyqqkzjwyooynxmtniyzuryyddjlqovdpwsertmqhdhffuontnqdmpvfuifkonlipowezacfchcpormwvgfzvhkvxczwoumkcnlstmbfyrbqgjwpzmhgeqljynszhyegzdgcpzzqouzbwqhxudkznrixssamcacjvzqlrfswrtaeotsqgxzgfvcyoanaymfpegqhtghrzwtgtsqrcqjqllazebuairlhupjbmqesizjwyzxnypopmcluweuuotnegrwiiqffkqwjpnvbuallzukgycjfhcyyqijtgfivpywlwmuazpdkiayjgktrstlpvemedqhmzicrtedvamnoemeejcceosivedbduruomdfcxfnxskriyjsznrwiyrlhbhspuepgpygpgijnumrakoizeddaoennnssuushtaprrwcmchyywgwyqzgxehipxdwrdfhtycjcvvufpaxebhjewgtfdzykozwhykbjusgeqoymbbgjvvznvhexlcwcglgtqnnrcyypcagngazzvpppxittkjerprwipjfswxzzygmxvvhcmekvtxtmgdcpfalcnncmfxqjpzsgtkvqpmxepsedgftdfhaeyqnigpmxqecwkxoavvxqttwpcecvftcwpzhtwkzguaecelrwttbhiripzlxewpwejxxrwfxqfpjytqojgyirlcrdewrpbqxctxuikgpzoxhgkvwdmadijmqmyegqlzodpzonhdhcacturzpcrlsssecpmfyxpuzrwtrvjlllykdrktegvilfjpnavxdrpsrwsmkcgsdvvhvkhczivgyptshnvisrwcltdhdfwufcjysbqrgrtqazsmoosasmgakkjozfknuwxqlzmkgjaizbrqakoibunekuyomzvfddwazozbflaqyphwmchicxmuyhmbekqcnqdcqnwbateyskxvkwcrybxisdyygqltguupwpeoqdrpvuioktuynkqppgkzujnogxqimzhzvpjspjrwmyeqreixuduipksqzvrsmnxnqvyecwtfsvdbpcybdecjdjuoxiroxnsnkgriwjbutqriowzvjywjzhcpqfbxokrmqhzdfcnejwdsevqantcflqlhlvydjjcfmpukwluskwnsqoxtxnhhuvofyhpwbzpamxgayshdzsjryzvxoxzpdeobqiyusbujadugxxowkhvpgwffeyvxqwahugitkjrhfhbimzvdlmrbygjshazxpzunfckenalaipidnronhypkfxzjtbmnwqqqbhpswpdalggwwrhgrmgwywsseevjjkaqkkehrplfzhshwhgpsiqfalbdohwdxfooxlqqfsovlmupvjyhcdxucgejxbubyasqaictoqjyabiunweipiekheiqobrwrmzezyswatdpxdcieyvguikxewoekhtkhqybynojncujmdaiulkfpwzqlnpvdtbrsvsbcddagtavjulxwpstlqtplqtustzjzoexrisclwldyoyamwwpjzyvmbrwdjyiubzysvxnnrhupflqxqvqjnqbonubjmfeccoijovxfzpouyukrccsrkvendggkdgonldstmedihwirvbkgonuojaboufkbqmolhgfewsdlfvpilgzljtrgfkqzmxdxysfmkvvtcjuyasqmzuopxbasgaabpagkmdfkyuzktpbcrttgtwtatcksttojwvnelgjjffaijnakabtaendzvmlkjtrsekigopnyrugksfluxkyojayopfacnywgwypzndwmsxhlmpusirgawkeivjbgkiyanaigjtixlpdxblwkapqauircaibydbrbfeqcynsduabybmbvgglqozuzajqkjervqnqmfvsqzzbrgotwxcgyqlnvjqacfjvtmnsrdflstniwzsvikwihyjflhpjewczhxyiedtdwvyxhwngeqgvlasoyltduzixkxgqkonxurpztgwktfwbrsxwowtrecqeyguiobttcvthrlascxdgccwldxpnseikrobujpuplbpoystfkjanjzyzjyjkndhtpgqdrptwubjjlnihfzjoztjljtiiparfkjnacruzxkevtwrzrxnpcfkpbibebonugichzhifawdckvqmwgajyhybjlvftmrcmagvhviudnphbmattgkrapuiwhzizpotbgbxkbzqcnfnytuuuwydldkvbhxvghvzrumzwzmcuplsaoyeyiilzcivupvwzytsfinyixqviokxpdszqsdxmrxwesyzbboxkihygkjlzqritosouwkhbaykqqyywcgproaspjyftkuyeyajgdmladuvtijqnwjqvnwcmdxrqrptibilmvmozpxdxmcqtknxkfytsvlvexmpsbrnyajmroyrclkjkskndypmtjgkycwneurltisbouakcaqcnijlgnduaqrftgnocdvsdahbtyybcaizbzkccdtmolfpzdbkmtdjldkkztmfehadmugxiyyrvexdcchkkokhjnikzayzjyafanmazquhwhcnnncszzrycwalbkszmvoogzynqmhybqcibofulxxwxpavmnxnlxixqtljmzimavcfcnfqfcemmtmssadrxwbptvxhrpjvyikypogvwgxpgqygvufapplbwcrmphcnxtnkwezhzkjgxykhcpdehixdxhctsxkxbbtlwsmmiuzplzyxdymhruxabzwvffsqwriujszwxythotbamldolarqsjeyndlvmaddiwsjwjcelwfnmpfpuamjhoxmhquleeuewonatdkslawenazzirrwxvytcbaqjuipzcittqkhsxppednfxnlcumjksxwndtpvnwcrlldvprqpmmtremknkiemplxdjnyuofxduqifefdedtxyuxgqvwlvzegmiyifmemyrkfnizkmrzbcgsmwgwbjzjaqvzzgnmpusgtlxpydzohpmepdpcrouwjhhcuyasipzuoabiiixpzmfskommqhheqlnyhxwiwmkeqotyiixsswvpqdjqncqndmlofewyqruvbqoqdrlzbnrvphsomrpyvhxhimggagaqfyaxomeqqlidzxagpuuewaxbuafycvomlyxjdbammxourcoyvgvldtyhgfqjdmqpnldmcdyjvcuelfmnsefhlfzimgbwhuleriejkoecjlkycdwwbjcclucqalskyzeimoamjnsbrlajnsjcuwwmejpldtpafeuehkztrysvezxjturogmtbcrviixjlthrpajesoaalhoztiararvljqztouotvmilpxtqntbfznmffawnpphzrdsoaetdjeikapgfamhjowtlwndntsrtpnirrxlsrdimnqqjvowowarmxhqqaqywqkesiwqotfrhlbofotzenjddglbdwaxffwipmzzbkpdclencmetifwsogjrpdhlginuldfxulexgljynrinbdctbvosdwqtflxhnizejkzpaojoofxpgijycnzbjypjkjnjdbywvfxafgxcnqhxmimmfsnlsfqlqiiwlzyfnbvkhgzmeoalqyoidmuzenelpfqzksfggmebewnxhfpmbcjguhgnmeetlbnstonpvkbtxkbtefmhkklsqhdrbuupqnnufdxzkiqeggykixxswabsftobycxpiothsagyddlbdqjpfzirnxurgonzowoitowvucqrzcxsyzyqicrvgfmfznakqmtxmgmsltgjlrglatxviwxvjzyhrstshljhcsoegzaiuvvmhvqskfrgvzeycgxnxatannwxalayyekdshyhqphprzcwaeiegvqbdfgyryonqkfnmfohdfbmdqxwbngwljpuxppqaljxcwzujzffyaqdiqlvzzalxfpeghftzmquqtzxyevbjrglucchmrnezjasicdnwgsnjlnubcizcyjxwxkvtbgovjsohtjfdfazyplhtusdiccnnoqcrifsakclhrbuokivielxxttjzblecdsgwfofvnnhixtuzoutgwkzjctvluzvvbhvzcrwqgmdpytalfiyvixewxetyqrptmeapkapwnpiopcyjvanumxwcdgxjroywvslcwcqchemzmhfnvkaopyeankzaouduyetiowhdfgjyjivxpenfgtxzbrdhayuyqykgqwcewsqnaiuezalcjgnpslguefwvsadctchatvfsjistemqllniihsoacjqwgpctziphsybaxhazdslpjvvpullcqouyalcehvapsplyfkzhyuniqxhfgvhxafovuuoiqfgovqsxelghpkvdfrgqhuwzxormatkivzbqvqcyviinycymmnnthdenwjqzzrkjmvvkoxhseeskapndecgbggsoglwzvtgkvornfpcfpvpjidrskaozwebgyqpekhdxemkvrogzxsweafkplnaapffhulcwilcfeqreciqekunqqiegbbbscpdlcvlcqfrnfhvqqwezssdezndidmmxsfcgdmgesmxxisaoiwzksxgamkzmycopiqmoxavesekctiwnpjbfrxbiqihgtvhlptgzsynjnymczfbemopcblmeozbjtmmlcvavkxthycigktuxixlxvrlholkuhijlmoqzblmhglvmcxpdkimluhwdbnqatxiqdanavutsnvoxthztpxanoptezjtwxxzgbhdvlkyvugjjawvdutzrtnbzzqboiwucpvrcfmkogbmdtbiomykkvrwjquhwohfurzytubnnfvnebxd"
power = 38894
modulo = 73463
k = 3098
hash_value = 3671

print(substring_hash(s, power, modulo, k, hash_value))

s = "leetcode"
power = 7
modulo = 20
k = 2
hash_value = 0

print(substring_hash(s, power, modulo, k, hash_value))

s = "fbxzaad"
power = 31
modulo = 100
k = 3
hash_value = 32

print(substring_hash(s, power, modulo, k, hash_value))
